<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" ignored="1" name="Test3" tests="2" failures="2" timestamp="16 Nov 2019 06:53:51 GMT" time="76.536" errors="0">
  <testcase name="sVerifycreationofUsers" time="66.363" classname="master.cbank.tests.VerifyCreatingusers">
    <failure type="java.lang.AssertionError" message="expected [Permissions] but found [Username is already in use. Please provide a new username.]">
      <![CDATA[java.lang.AssertionError: expected [Permissions] but found [Username is already in use. Please provide a new username.]
at master.cbank.tests.VerifyCreatingusers.sVerifycreationofUsers(VerifyCreatingusers.java:67)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sVerifycreationofUsers -->
  <testcase name="sAssignpersmission" time="0.429" classname="master.cbank.tests.VerifyCreatingusers">
    <failure type="java.lang.AssertionError" message="unable to complete login">
      <![CDATA[java.lang.AssertionError: unable to complete login
at master.cbank.pages.LoginPage.Login(LoginPage.java:69)
at master.cbank.tests.VerifyCreatingusers.sAssignpersmission(VerifyCreatingusers.java:105)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- sAssignpersmission -->
  <testcase name="sVerifyActivation" time="0.0" classname="master.cbank.tests.VerifyCreatingusers">
    <ignored/>
  </testcase> <!-- sVerifyActivation -->
</testsuite> <!-- Test3 -->
